### ISSUE TITLE
Animated Links on Hover

### ISSUE THREAD

**Issue by KittenCodes** [KittenCodes/WinuSoft-Web-Design#1]
```css
/* ref: https://tobiasahlin.com/blog/css-trick-animating-link-underlines/
*/
li.menu-item > a {
  position: relative;
}
li.menu-item > a:before {
  content: "";
  position: absolute;
  width: 100%;
  height: 2px;
  bottom: 0;
  left: 0;
  background-color: #ccc;
  visibility: hidden;
  -webkit-transform: scaleX(0);
  transform: scaleX(0);
  -webkit-transition: all 0.3s ease-in-out 0s;
  transition: all 0.3s ease-in-out 0s;
}
li.menu-item > a:hover:before {
  visibility: visible;
  -webkit-transform: scaleX(1);
  transform: scaleX(1);
}
li.menu-item {
  padding: 4px 8px;
}
```
