### ISSUE TITLE
Custom Search Form using Linearicons

### ISSUE THREAD

**Issue by KittenCodes** [KittenCodes/WinuSoft-Web-Design#3]
```html
<div id="search-5" class="widget widget_search">
  <form class="search-form" method="get" action="<?php echo get_site_url(); ?>" _lpchecked="1">
	<button class="btn btn-style-4 icon-btn f-right" type="submit"><i class="licon-magnifier"></i></button>
	<div class="wrapper">
		<input type="text" autocomplete="off" id="s" name="s" placeholder="Search" value="">
	</div>
  </form>
</div>
```

```css
.widget {
    border-radius: 4px;
    background-color: #fff;
    box-shadow: 0 1px 2px 1px rgba(0,0,0, .07);
    position: relative;
    overflow: hidden;
}

.widget:before {
    position: absolute;
    width: 100%;
    height: 3px;
    background: -moz-linear-gradient(left, rgba(81,163,255,0.8) 0%, rgba(215,32,51,0.8) 100%);
    background: -webkit-linear-gradient(left, rgba(81,163,255,0.8) 0%,rgba(215,32,51,0.8) 100%);
    background: linear-gradient(to right, rgba(81,163,255,0.8) 0%,rgba(215,32,51,0.8) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#cc51a3ff', endColorstr='#ccd72033',GradientType=1 );
    content: "";
    display: block;
}

.widget_search form {
    margin: 0;
    padding: 15px 20px;
    display: block;
}

form {
    text-align: left;
}

.btn.icon-btn {
    font-size: 1em;
    padding: 10px 13px 8px;
    text-align: center;
}

[class*="btn"].btn-style-4 {
    background: #d72033;
    color: #fff;
    display: inline-block;
    vertical-align: middle;
    position: relative;
    line-height: 1.500em;
    letter-spacing: 0.8px;
    z-index: 1;  
}
.search-form .btn {
    border-radius: 0 4px 4px 0;
}

.f-right {
    float: right;
}

.licon-magnifier:before {
    width: auto;
    margin: 0;
    padding: 0;
}
.licon-magnifier:before {
    content: "\e922";
}

.wrapper {
    overflow: hidden;
}

.wrapper:after, .wrapper:before {
    content: "";
    display: table;
}

.widget .search-form .wrapper > input[type="text"], select {
    border-radius: 4px 0 0 4px;
    border-right: none;
    width: 100%;
    color: #777;
    height: 48px;
    font-size: 1em;
    padding: 10px 20px;
    border: 1px solid #ddd;
    text-align: left;
    background-color: #fff;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    -webkit-transition: box-shadow .35s ease, border-color .35s ease;
    transition: box-shadow .35s ease, border-color .35s ease;  
}

.search-form .btn {
border: none;
}

.widget .search-form .wrapper > input[type="text"] {
    border-right: 0px;
}

input:not([type="submit"]):focus, textarea:focus {
    border-color: rgba(3, 142, 211, .5);
    box-shadow: 0 0 10px 0 rgba(3, 142, 211, .2);
    -moz-appearance: none;
    outline: 0 none transparent;
}

.licon-magnifier {
    font-family: 'Linearicons';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-feature-settings: "liga";
    -moz-font-feature-settings: "liga=1";
    -moz-font-feature-settings: "liga";
    -ms-font-feature-settings: "liga" 1;
    -o-font-feature-settings: "liga";
    font-feature-settings: "liga";
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

.licon-magnifier:before {
    content: "\e922";
}

@font-face {
	font-family: 'Linearicons';
	src: url('../../fonts/Linearicons.ttf') format('truetype');
	font-weight: normal;
	font-style: normal;
}
```

Rename the attached Linearicons file to ttf and add to /fonts/.

![Linearicons](https://user-images.githubusercontent.com/18448481/71579843-3b186f80-2af6-11ea-8cef-ea3f29d38797.jpg)
